#!/bin/bash
set -e

staged_files=$(git diff --cached --name-only)

if echo "$staged_files" | grep -q "^server/"; then
  pnpm --filter ./server lintformat
fi

if echo "$staged_files" | grep -q "^client/"; then
  pnpm --filter ./client lintformat
fi